# Generated by Django 5.2.4 on 2025-08-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0002_country_alter_city_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=156, unique=True),
        ),
    ]
