# Generated by Django 5.2.4 on 2025-08-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0003_alter_country_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityCSVUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='csv/')),
            ],
        ),
    ]
