# Generated by Django 5.2.4 on 2025-08-20 11:08

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0004_citycsvupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=156, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=156, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='citycsvupload',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/Users/apow/Desktop/DemoFile/Demo')), upload_to='csv/'),
        ),
    ]
