# Generated by Django 5.2.4 on 2025-08-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0005_category_alter_citycsvupload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='slug',
            field=models.SlugField(blank=True, max_length=156, unique=True, null=True),
        ),
    ]
