# Generated by Django 5.2.4 on 2025-08-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0006_country_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.SlugField(blank=True, max_length=156, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=models.SlugField(blank=True, max_length=156, unique=True),
        ),
    ]
