# Generated by Django 5.2.4 on 2025-08-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0007_city_slug_alter_country_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(blank=True, max_length=156, null=True),
        ),
    ]
