# Generated by Django 5.2.4 on 2025-08-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0008_alter_city_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='countries', to='Map.category'),
        ),
    ]
